### PR TITLE
fix: redirect static-router/doc/master to stable docs (#568)

### LINKED ISSUE #568: Outdated (Rust 1.17.0) docs hosted on static.rust-lang.org
### What needs to be fixed?

Old docs, with "master" in the URL, are accessible from static.rust-lang.org. This may show up in web search results, older forum posts, etc.

### Page(s) Affected

https://static.rust-lang.org/doc/master/rust.html
https://static.rust-lang.org/doc/master/reference.html

### Suggested Improvement

Redirect to the current reference documentation:  https://doc.rust-lang.org/reference/

### PR DESCRIPTION
**Pull request by softmoth**
## Testing

I didn't test this, I'm not sure how to do so.

## Rationale for `stable`

I decided that a redirect to `//doc.rust-lang.org/stable/*` makes the most sense. While the `doc-router` redirects `/master` to `/nightly`, that is a mistake that could be happening with current users (e.g., someone is looking at `stable` docs and wants the latest, so they just change the URL in the browser to `master`).

This `static-router` redirect should really only be hit when coming from an old forum post or similar (it was Rust 0.17 docs, after all). Since [`stable` is the default][stable-default] for any miscellaneous path on `doc-router`, it seems like the appropriate redirect target here.

[stable-default]: https://github.com/rust-lang/simpleinfra/blob/5a272d1d52cd099280e39584543f0dbfa26c86bc/terragrunt/modules/release-distribution/lambdas/doc-router/index.js#L125

## Redirecting to doc.rust-lang.org

I decided to redirect to `//doc.rust-lang.org` instead of stay on `//static.rust-lang.org`, because there could be some helpful error handling or other redirects in `doc-router` that we'd want to take advantage of. Also, it is the preferred entry point for all documentation, so it's best to keep `static` as an implementation detail when possible.

Close #568

### CODE REVIEW

File: terragrunt/modules/release-distribution/lambdas/static-router/index.js [hunk 1]
```diff
@@ -35,5 +35,12 @@ echo "    curl https://sh.rustup.rs -sSf | sh"
         return redirect('https://sh.rustup.rs', body, callback);
     }
 
+    // Links to `/doc/master/*` are probably from old external sources, so send
+    // them back through the doc site to take advantage of any helpful error
+    // handling that may be defined there
+    if (request.uri.startsWith('/doc/master')) {
+        return redirect('//doc.rust-lang.org/stable' + request.uri.slice(11), callback);
```
Comment (MarcoIeni) [inline terragrunt/modules/release-distribution/lambdas/static-router/index.js:42]:
```suggestion
        return redirect('https://doc.rust-lang.org/stable' + request.uri.slice(11), callback);
```
I think it's better if we force https 👍

Comment (MarcoIeni) [reply terragrunt/modules/release-distribution/lambdas/static-router/index.js]: done in 5b84e4d

**Comment by MarcoIeni** [comment]
I applied the changes in the staging environment.

https://cloudfront-dev-static.rust-lang.org/doc/master/rust.html works!
`reference.html` is not working yet because of caching on my browser probably.

`index.js` is for cloudfront. We also need to update fastly. I forgot to mention this in the issue, sorry!

Here's the location:

https://github.com/softmoth/simpleinfra/blob/8df16d45f2b95e77081928ea9f66f53267b91e80/terragrunt/modules/release-distribution/fastly-static.tf#L97

Do you want to look into that as well?

**Comment by softmoth** [comment]
Thank you for fixing the `body` bug. My attention span is that of a gnat, apparently.

I've made a stab at the fastly VCL change. I didn't test it either, but hopefully it's correct.

**Comment by MarcoIeni** [comment]
> My attention span is that of a gnat, apparently.

We should try to add a linter for that code honestly 😅

Thanks, I'll test this soon!

File: terragrunt/modules/release-distribution/fastly-static.tf [hunk 2]
```diff
@@ -115,6 +115,26 @@ resource "fastly_service_vcl" "static" {
     VCL
   }
 
+  snippet {
+    # This was an abandoned copy of Rust 1.17.0-era docs; redirect to current docs
+    name    = "redirect /doc/master to /stable"
+    type    = "error"
```
Comment (jdno) [inline terragrunt/modules/release-distribution/fastly-static.tf:121]: The snippet will not be executed, since we never make it to the `error` state in the [VCL lifecycle](https://www.fastly.com/documentation/guides/vcl/using/). That's why the existing snippet that redirects `rustup.sh` first has a snippet that detects requests to that endpoint and then fails them with a custom error that we're handling manually.

```vcl
snippet {
  name    = "detect rustup.sh requests"
  type    = "recv"
  content = <<-VCL
    if (req.url ~ "^\/rustup\.sh$") {
      error 618 "redirect";
    }
  VCL
}
```

We need something like this for the docs as well. I suggest that we use a new error code (e.g. `619`), and then replicate how `rustup.sh` is handled.

File: terragrunt/modules/release-distribution/fastly-static.tf [hunk 3]
```diff
@@ -115,6 +115,26 @@ resource "fastly_service_vcl" "static" {
...
+    content = <<-VCL
+      if (req.url ~ "^\/doc/master(\/|$)")?$") {
```
Comment (jdno) [inline terragrunt/modules/release-distribution/fastly-static.tf:123]: If I'm not counting wrong, there's a `(` missing or a `)` too many somewhere. 😅

**Review by jdno — CHANGES_REQUESTED** [review]
Thanks for working on this. If you need any help with Fastly, feel free to ping me. 🙂

File: terragrunt/modules/release-distribution/fastly-static.tf (hunk 3 above)
Comment (MarcoIeni) [reply terragrunt/modules/release-distribution/fastly-static.tf]: I tried to simplify the regex in https://github.com/rust-lang/simpleinfra/pull/571/commits/cdd0f7b54bf239773c12a60d2d45083aec4dab11

**Comment by MarcoIeni** [comment]
I think this is ready to be tested. What do you think JD?

One concern I have is that previous links pointing to docs will now be empty. e.g. https://static.rust-lang.org/doc/master/reference.html#whitespace will now point to https://doc.rust-lang.org/stable/reference.html#whitespace, so people need to look for the info they were looking for again in the new docs.

I think this is fine, since imo is better if people spend a few seconds more for their research but at least hey find up-to-date docs. Plus, the rust reference book has a search box 👍

File: terragrunt/modules/release-distribution/fastly-static.tf [hunk 4]
```diff
@@ -115,6 +125,26 @@ resource "fastly_service_vcl" "static" {
...
+    content = <<-VCL
+      if (obj.status == 619 && obj.response == "redirect") {
+        set obj.status = 301;
+        set obj.response = "Moved permanently";
+        set obj.http.Location = regsub(req.url, "^\/doc\/master", "https://doc.rust-lang.org/stable");
+
+        synthetic {"
+      #!/bin/bash
+      echo "The documentation now lives under doc.rust-lang.org"
+        "};
```
Comment (MarcoIeni) [inline terragrunt/modules/release-distribution/fastly-static.tf:141]:
```suggestion
```
not needed

**Comment by MarcoIeni** [comment]
Applied to dev.

https://cloudfront-dev-static.rust-lang.org/doc/master/rust.html and https://fastly-dev-static.rust-lang.org/doc/master/rust.html work!

I'm squashing into main and then opening another pr to update the git ref. I'm not force-pushing because I don't want softmoth to loose credit for their work 👍

**Review by MarcoIeni — APPROVED** [review]

**Review by jdno — APPROVED** [review]
